### ISSUE TITLE
Trying to get my Spotify Phoniebox back...

### ISSUE THREAD

**Issue by Micharius** [maahn/piCorePhonie#1]
Hello and warm thanks for helping us Phoniebox-Spotify-owners out!
I'm following your footsteps and instructions, but some questions already appeared

**piCore Extension**

- pit
Unfortunately, I can't find any extension with this name. Do you have more informations about that extension?

- gcc
Is that actually _gcc_libs_?

- glibc-base
Is that actually _glibc_base_dev_?

- Linux-5.10 api headers
Probably _linux-5.10.y_api_headers_ ?

**Solved problem**
Newbie fault: With the default partition of 64MB, I ran into strange error messsages, until I resized the partition. May someting you could point out in the wiki?

**OnOff Shim**
A dummy like me had to learn, that I needed to press the button '_Install Monitor_' as well....

Many thanks for any help in advance,

Kind regards,

Micharius

**Comment by maahn** [comment]
Thanks for pointing these issues out, I updated the instructions 267d35c1e9ef04fd5353e4add66ef3911e867828.

**Comment by Micharius** [comment]
Thanx for your help...I continue to follow your instructions...
