### ISSUE TITLE
Little bit further, but still

### ISSUE THREAD

**Issue by Micharius** [maahn/piCorePhonie#2]
Hi - I continued to install, managed to creat an LMS server an connect my Spotify account to it.
However, after following your instructions, I can't install _Spidev_ and _RPi.GPIO_. The installations crashes like this for _Spidev_ (the RPi.GPIO output is almost the same):

```
Collecting spidev
  Using cached spidev-3.5.tar.gz (10 kB)
Building wheels for collected packages: spidev
  Building wheel for spidev (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4b3_e3l1/spidev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4b3_e3l1/spidev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-r0scr535
       cwd: /tmp/pip-install-4b3_e3l1/spidev/
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'spidev' extension
  creating build
  creating build/temp.linux-aarch64-3.8
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a+crc -mtune=cortex-a53 -O2 -pipe -march=armv8-a+crc -mtune=cortex-a53 -O2 -pipe -fPIC -I/usr/local/include/python3.8 -c spidev_module.c -o build/temp.linux-aarch64-3.8/spidev_module.o
  spidev_module.c:28:10: fatal error: Python.h: No such file or directory
     28 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for spidev
  Running setup.py clean for spidev
Failed to build spidev
Installing collected packages: spidev
    Running setup.py install for spidev ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4b3_e3l1/spidev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4b3_e3l1/spidev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2c71ntzl/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /root/.local/include/python3.8/spidev
         cwd: /tmp/pip-install-4b3_e3l1/spidev/
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'spidev' extension
    creating build
    creating build/temp.linux-aarch64-3.8
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=armv8-a+crc -mtune=cortex-a53 -O2 -pipe -march=armv8-a+crc -mtune=cortex-a53 -O2 -pipe -fPIC -I/usr/local/include/python3.8 -c spidev_module.c -o build/temp.linux-aarch64-3.8/spidev_module.o
    spidev_module.c:28:10: fatal error: Python.h: No such file or directory
       28 | #include <Python.h>
          |          ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4b3_e3l1/spidev/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4b3_e3l1/spidev/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2c71ntzl/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /root/.local/include/python3.8/spidev Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 22.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
```
Of cource, _GCC_ is installed as extentions. Some sources advise to install _compilec_  as well, I tried this, but it didn't work.

Do you have any idea whats causing the error?

Warm regards,

Micharius

**Comment by maahn** [comment]
Looks to me like Python3.8-dev is missing, are you sure you installed the extension?

**Comment by Micharius** [comment]
This is weird...I startet with a new image from PiCore...when I loaded the _Python3.8-dev_ I noticed, that it is obivously loading a completely different image (_sgqlite3_) in the background (see screenshot)...to be continued...
![Screenshot 2022-05-28 162634](https://user-images.githubusercontent.com/88677184/170830034-62aa566b-bdde-453b-899f-344232c279f9.png)

**Comment by maahn** [comment]
This is not an error, SQLlite is a dependency and is automatically installed first

**Comment by Micharius** [comment]
But shouldn't _Python-dev_ be listed as a package in _Installed_ after? It wasn't in my cause, only the _squlite3_ appeared. Concerning my problems, I assumed this could be the reason

**Comment by maahn** [comment]
I remember I was also confused because it looked like the extensions didn’t properly install, but that was only a problem with the GUI and everything worked. Yes, the extension should appear in the list with the installed packages, together with all the automatically installed dependencies like SQLlite and the normal Python3.8 package. If it does not even if you have enough disk space available, I‘m afraid you have to ask in the support forums of PiCorePlayer.

**Comment by Micharius** [comment]
Solved the problem - I think, in the first attempt, the _Python3.8-dev_ went only half through the installation process due the lack of disk space. The systems thought, it was installed, in reality, not all the packages were loaded. I could finally finish the installation steps.
Only to realize, that I don't have a RFID RC-522 reader...mine is a USB-connectec one, basically a Keyboard that types the numbers from the card.
So my idea to get a quick fix for the Spotify catatrophe is back to square one. I obviously need to learn more Python to solve this problem.
But thanks for helping anyway!
